param(
	[string]$Root = $PSScriptRoot
)

$ErrorActionPreference = 'Stop'

$sourcesFile = Join-Path $Root 'standalone_sources.txt'
$configHeader = 'mgba_wrap_config.h'

function Get-WrapperContent {
	param(
		[string]$NormalizedPath,
		[string]$HeaderName
	)

	$content = @(
		'/* Auto-generated by generate_wrappers.ps1. */'
		('#include "' + $HeaderName + '"')
	)

	switch ($NormalizedPath) {
		'src/platform/windows/memory.c' {
			$content += @(
				'#if defined(_WIN32)'
				'#include "upstream/src/platform/windows/memory.c"'
				'#else'
				'#include "upstream/src/util/memory.c"'
				'#endif'
			)
		}

		'src/platform/windows/vfs-w32.c' {
			$content += @(
				'#if defined(_WIN32)'
				'#include "upstream/src/platform/windows/vfs-w32.c"'
				'#else'
				'#include "upstream/src/util/vfs/vfs-dirent.c"'
				'#endif'
			)
		}

		default {
			$content += '#include "upstream/' + $NormalizedPath + '"'
		}
	}

	return $content
}

if (-not (Test-Path $sourcesFile)) {
	throw "Source list not found: $sourcesFile"
}

$wrapperPattern = Join-Path $Root 'mgba_wrap_*.c'
Get-ChildItem -Path $wrapperPattern -ErrorAction SilentlyContinue | Remove-Item -Force

$lines = Get-Content $sourcesFile | Where-Object {
	$_ -and -not $_.TrimStart().StartsWith('#')
}

foreach ($relativePath in $lines) {
	$trimmed = $relativePath.Trim()
	if ($trimmed -eq 'mgba_version_stub.c') {
		continue
	}

	$normalized = $trimmed.Replace('\', '/')
	$wrapperName = 'mgba_wrap_' + (($normalized -replace '[^A-Za-z0-9]+', '_').Trim('_')) + '.c'
	$wrapperPath = Join-Path $Root $wrapperName
	$content = Get-WrapperContent -NormalizedPath $normalized -HeaderName $configHeader

	Set-Content -Path $wrapperPath -Value $content -Encoding ASCII
}

Write-Host "Generated wrappers in $Root"
