/* Auto-generated by generate_wrappers.ps1. */
#include "mgba_wrap_config.h"
#if defined(_WIN32)
#include "upstream/src/platform/windows/vfs-w32.c"
#else
#include "upstream/src/util/vfs/vfs-dirent.c"
#endif
