/* Auto-generated by generate_wrappers.ps1. */
#include "awave_wrap_config.h"

#define libAICA_Term fbneo_awave_libAICA_Term_impl
#include "flycast/core/hw/aica/aica.cpp"
#undef libAICA_Term

void aica_Term();

void libAICA_Term()
{
	fbneo_awave_libAICA_Term_impl();
	aica_Term();
	aica_schid = -1;
}
