/* Auto-generated by generate_wrappers.ps1. */
#include "awave_wrap_config.h"

#define rend_single_frame flycast_rend_single_frame_original
#include "flycast/core/hw/pvr/Renderer_if.cpp"
#undef rend_single_frame

static bool fbneo_awave_seen_presented_scene = false;

extern "C" void fbneo_awave_reset_present_filter(void)
{
	fbneo_awave_seen_presented_scene = false;
}

// rend_single_frame: Only present isRenderFramebuffer frames after we've seen
// at least one real 3D/TA frame. This prevents startup garbage frames while
// keeping normal operation stable.
bool rend_single_frame(void)
{
	while (true)
	{
		if (_pvrrc == NULL)
		{
			do
			{
#if !defined(TARGET_NO_THREADS)
				if (settings.rend.ThreadedRendering)
				{
					if (!rs.Wait(100))
						return false;
					if (do_swap)
					{
						do_swap = false;
						rs.Set();
						if (fbneo_awave_seen_presented_scene)
							return true;
						continue;
					}
				}
#endif
				_pvrrc = DequeueRender();

				if (!settings.rend.ThreadedRendering && _pvrrc == NULL)
					return false;
			}
			while (!_pvrrc);
		}

		const bool framebufferOnly = _pvrrc->rend.isRenderFramebuffer;
		if ((_pvrrc->rend.isRTT || framebufferOnly) && swap_pending)
		{
			swap_pending = false;
			// Skip framebufferOnly frames until we've seen a real 3D/TA frame
			if (framebufferOnly && !fbneo_awave_seen_presented_scene)
			{
				FinishRender(_pvrrc);
				_pvrrc = 0;
				continue;
			}
			if (!framebufferOnly)
				fbneo_awave_seen_presented_scene = true;
			return true;
		}

		bool do_swp = rend_frame(_pvrrc, true);
		swap_pending = do_swp && !_pvrrc->rend.isRenderFramebuffer && FB_R_SOF1 != FB_W_SOF1
				 && settings.rend.ThreadedRendering && settings.rend.DelayFrameSwapping;

		if (settings.rend.ThreadedRendering && _pvrrc->rend.isRTT)
			re.Set();

		FinishRender(_pvrrc);
		_pvrrc = 0;

		if (do_swp && !swap_pending)
		{
			// Skip framebufferOnly frames until we've seen a real 3D/TA frame
			if (framebufferOnly && !fbneo_awave_seen_presented_scene)
				continue;
			if (!framebufferOnly)
				fbneo_awave_seen_presented_scene = true;
			return true;
		}
	}
}
