/* Auto-generated by generate_wrappers.ps1. */
#include "awave_wrap_config.h"

#define aica_Term fbneo_awave_aica_Term_impl
#include "flycast/core/hw/aica/aica_if.cpp"
#undef aica_Term

void aica_Term()
{
	fbneo_awave_aica_Term_impl();
	rtc_schid = -1;
	dma_sched_id = -1;
}
