param(
	[string]$Root = $PSScriptRoot
)

$ErrorActionPreference = 'Stop'

$sourcesFile = Join-Path $Root 'standalone_sources.txt'
$configHeader = 'awave_wrap_config.h'

if (-not (Test-Path $sourcesFile)) {
	throw "Source list not found: $sourcesFile"
}

Get-ChildItem -Path (Join-Path $Root 'awave_wrap_*') -ErrorAction SilentlyContinue |
	Where-Object { $_.Extension -in '.c', '.cpp' } |
	Remove-Item -Force

$lines = Get-Content $sourcesFile | Where-Object {
	$_ -and -not $_.TrimStart().StartsWith('#')
}

foreach ($relativePath in $lines) {
	$rawPath = $relativePath.Trim()
	$includeRoot = '../../../../../../flycast/'
	$normalized = $rawPath.Replace('\', '/')

	if ($normalized.StartsWith('fbneo:')) {
		$normalized = $normalized.Substring(6)
		$includeRoot = '../../../../'
	} elseif ($normalized.StartsWith('flycast:')) {
		$normalized = $normalized.Substring(8)
	}

	$wrapperStem = 'awave_wrap_' + (($normalized -replace '[^A-Za-z0-9]+', '_').Trim('_'))
	$wrapperExt = if ($normalized.EndsWith('.c')) { '.c' } else { '.cpp' }
	$wrapperPath = Join-Path $Root ($wrapperStem + $wrapperExt)

	$content = @(
		'/* Auto-generated by generate_wrappers.ps1. */',
		('#include "' + $configHeader + '"'),
		('#include "' + $includeRoot + $normalized + '"')
	)

	Set-Content -Path $wrapperPath -Value $content -Encoding ASCII
}

Write-Host "Generated wrappers in $Root"
